remote_theme: mmistakes/minimal-mistakes

title: "Dominic Minischetti"
description: "My personal website"
url: "https://dminischetti.github.io"
baseurl: ""

author:
  name: "Dominic Minischetti"
  email: "your-email@example.com"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
