remote_theme: mmistakes/minimal-mistakes@4.26.2

title: "Dominic Minischetti"
description: "My personal website"
url: "https://dminischetti.github.io"
baseurl: ""

author:
  name: "Dominic Minischetti"
  email: "dominic.minischetti@gmail.com"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Dark Mode Support
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      classes: "dark-mode"
